version: '3'

services:

  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
      - ./db-config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend-dev
    restart: always
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    expose:
      - ${BACKEND_PORT}
    volumes:
      - ./backend/:/home/node/app/:rw
      - /home/node/app/node_modules/
      - ./files/:/home/node/files/:rw
    command: npm run start:dev
    depends_on:
      - database
