version: '3'

services:

  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - JWT_SECRET=${JWT_SECRET}

    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
      - ./db-config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - skillsphere

  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend-prod
    restart: always
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    expose:
      - ${BACKEND_PORT}
    networks:
      - skillsphere

networks:
  skillsphere:
    driver: bridge
    external: true
